/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module "vue-router/auto/routes" {
  export interface RouteNamedMap {
    "/": RouteRecordInfo<"/", "/", Record<never, never>, Record<never, never>>
    "/[...all]": RouteRecordInfo<
      "/[...all]",
      "/:all(.*)",
      { all: ParamValue<true> },
      { all: ParamValue<false> }
    >
    "/about": RouteRecordInfo<
      "/about",
      "/about",
      Record<never, never>,
      Record<never, never>
    >
    "/blog/": RouteRecordInfo<
      "/blog/",
      "/blog",
      Record<never, never>,
      Record<never, never>
    >
    "/blog/better-api-testing-capabilities-and-more": RouteRecordInfo<
      "/blog/better-api-testing-capabilities-and-more",
      "/blog/better-api-testing-capabilities-and-more",
      Record<never, never>,
      Record<never, never>
    >
    "/blog/hoppscotch-wrapped-2023": RouteRecordInfo<
      "/blog/hoppscotch-wrapped-2023",
      "/blog/hoppscotch-wrapped-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/blog/introducing-hoppscotch-desktop-application": RouteRecordInfo<
      "/blog/introducing-hoppscotch-desktop-application",
      "/blog/introducing-hoppscotch-desktop-application",
      Record<never, never>,
      Record<never, never>
    >
    "/blog/introducing-hoppscotch-enterprise-edition": RouteRecordInfo<
      "/blog/introducing-hoppscotch-enterprise-edition",
      "/blog/introducing-hoppscotch-enterprise-edition",
      Record<never, never>,
      Record<never, never>
    >
    "/blog/introducing-secret-variables": RouteRecordInfo<
      "/blog/introducing-secret-variables",
      "/blog/introducing-secret-variables",
      Record<never, never>,
      Record<never, never>
    >
    "/blog/sample-post": RouteRecordInfo<
      "/blog/sample-post",
      "/blog/sample-post",
      Record<never, never>,
      Record<never, never>
    >
    "/brand": RouteRecordInfo<
      "/brand",
      "/brand",
      Record<never, never>,
      Record<never, never>
    >
    "/careers": RouteRecordInfo<
      "/careers",
      "/careers",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/": RouteRecordInfo<
      "/changelog/",
      "/changelog",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/00-00-0000": RouteRecordInfo<
      "/changelog/00-00-0000",
      "/changelog/00-00-0000",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/02-06-2023": RouteRecordInfo<
      "/changelog/02-06-2023",
      "/changelog/02-06-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/05-06-2023": RouteRecordInfo<
      "/changelog/05-06-2023",
      "/changelog/05-06-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/08-11-2023": RouteRecordInfo<
      "/changelog/08-11-2023",
      "/changelog/08-11-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/11-04-2023": RouteRecordInfo<
      "/changelog/11-04-2023",
      "/changelog/11-04-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/11-05-2023": RouteRecordInfo<
      "/changelog/11-05-2023",
      "/changelog/11-05-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/12-06-2023": RouteRecordInfo<
      "/changelog/12-06-2023",
      "/changelog/12-06-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/14-11-2023": RouteRecordInfo<
      "/changelog/14-11-2023",
      "/changelog/14-11-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/15-10-2023": RouteRecordInfo<
      "/changelog/15-10-2023",
      "/changelog/15-10-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/18-07-2023": RouteRecordInfo<
      "/changelog/18-07-2023",
      "/changelog/18-07-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/18-09-2023": RouteRecordInfo<
      "/changelog/18-09-2023",
      "/changelog/18-09-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/19-12-2023": RouteRecordInfo<
      "/changelog/19-12-2023",
      "/changelog/19-12-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/23-04-2023": RouteRecordInfo<
      "/changelog/23-04-2023",
      "/changelog/23-04-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/24-12-2023": RouteRecordInfo<
      "/changelog/24-12-2023",
      "/changelog/24-12-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/27-06-2023": RouteRecordInfo<
      "/changelog/27-06-2023",
      "/changelog/27-06-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/changelog/31-08-2023": RouteRecordInfo<
      "/changelog/31-08-2023",
      "/changelog/31-08-2023",
      Record<never, never>,
      Record<never, never>
    >
    "/community": RouteRecordInfo<
      "/community",
      "/community",
      Record<never, never>,
      Record<never, never>
    >
    "/company": RouteRecordInfo<
      "/company",
      "/company",
      Record<never, never>,
      Record<never, never>
    >
    "/contact": RouteRecordInfo<
      "/contact",
      "/contact",
      Record<never, never>,
      Record<never, never>
    >
    "/download": RouteRecordInfo<
      "/download",
      "/download",
      Record<never, never>,
      Record<never, never>
    >
    "/features": RouteRecordInfo<
      "/features",
      "/features",
      Record<never, never>,
      Record<never, never>
    >
    "/pricing": RouteRecordInfo<
      "/pricing",
      "/pricing",
      Record<never, never>,
      Record<never, never>
    >
    "/privacy": RouteRecordInfo<
      "/privacy",
      "/privacy",
      Record<never, never>,
      Record<never, never>
    >
    "/products/": RouteRecordInfo<
      "/products/",
      "/products",
      Record<never, never>,
      Record<never, never>
    >
    "/products/cli": RouteRecordInfo<
      "/products/cli",
      "/products/cli",
      Record<never, never>,
      Record<never, never>
    >
    "/products/cloud": RouteRecordInfo<
      "/products/cloud",
      "/products/cloud",
      Record<never, never>,
      Record<never, never>
    >
    "/products/enterprise": RouteRecordInfo<
      "/products/enterprise",
      "/products/enterprise",
      Record<never, never>,
      Record<never, never>
    >
    "/products/self-host": RouteRecordInfo<
      "/products/self-host",
      "/products/self-host",
      Record<never, never>,
      Record<never, never>
    >
    "/resources": RouteRecordInfo<
      "/resources",
      "/resources",
      Record<never, never>,
      Record<never, never>
    >
    "/solutions/": RouteRecordInfo<
      "/solutions/",
      "/solutions",
      Record<never, never>,
      Record<never, never>
    >
    "/solutions/cloud": RouteRecordInfo<
      "/solutions/cloud",
      "/solutions/cloud",
      Record<never, never>,
      Record<never, never>
    >
    "/solutions/developers": RouteRecordInfo<
      "/solutions/developers",
      "/solutions/developers",
      Record<never, never>,
      Record<never, never>
    >
    "/solutions/education": RouteRecordInfo<
      "/solutions/education",
      "/solutions/education",
      Record<never, never>,
      Record<never, never>
    >
    "/solutions/enterprises": RouteRecordInfo<
      "/solutions/enterprises",
      "/solutions/enterprises",
      Record<never, never>,
      Record<never, never>
    >
    "/solutions/self-host": RouteRecordInfo<
      "/solutions/self-host",
      "/solutions/self-host",
      Record<never, never>,
      Record<never, never>
    >
    "/solutions/teams": RouteRecordInfo<
      "/solutions/teams",
      "/solutions/teams",
      Record<never, never>,
      Record<never, never>
    >
    "/terms": RouteRecordInfo<
      "/terms",
      "/terms",
      Record<never, never>,
      Record<never, never>
    >
  }
}

declare module "vue-router/auto" {
  import type { RouteNamedMap } from "vue-router/auto/routes"

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
  > = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
  > = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
  > = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
  > = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
  > =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> =
    RouteNamedMap[Name]["params"]
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> =
    RouteNamedMap[Name]["paramsRaw"]

  export function useRouter(): RouterTyped
  export function useRoute<
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
  >(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(
    guard: NavigationGuard<RouteNamedMap>
  ): void
  export function onBeforeRouteUpdate(
    guard: NavigationGuard<RouteNamedMap>
  ): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from "unplugin-vue-router/runtime"
}

declare module "vue-router" {
  import type { RouteNamedMap } from "vue-router/auto/routes"

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
