// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementGradient: typeof import('./components/AnnouncementGradient.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LandingAnnouncement: typeof import('./components/LandingAnnouncement.vue')['default']
    LandingFeatures: typeof import('./components/LandingFeatures.vue')['default']
    LandingHero: typeof import('./components/LandingHero.vue')['default']
    LucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    LucideLightbulb: typeof import('~icons/lucide/lightbulb')['default']
    LucideMoon: typeof import('~icons/lucide/moon')['default']
    LucideSun: typeof import('~icons/lucide/sun')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
