// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonPrimary: typeof import('./components/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./components/ButtonSecondary.vue')['default']
    ChangelogCard: typeof import('./components/ChangelogCard.vue')['default']
    ChangelogIndicator: typeof import('./components/ChangelogIndicator.vue')['default']
    ChangelogTree: typeof import('./components/ChangelogTree.vue')['default']
    ContibutorBubble: typeof import('./components/ContibutorBubble.vue')['default']
    FeatureExplanation: typeof import('./components/FeatureExplanation.vue')['default']
    FeatureHero: typeof import('./components/FeatureHero.vue')['default']
    HomeFooter: typeof import('./components/HomeFooter.vue')['default']
    HomeHeader: typeof import('./components/HomeHeader.vue')['default']
    LandingAnnouncement: typeof import('./components/LandingAnnouncement.vue')['default']
    LandingContributors: typeof import('./components/LandingContributors.vue')['default']
    LandingCTA: typeof import('./components/LandingCTA.vue')['default']
    LandingFeatures: typeof import('./components/LandingFeatures.vue')['default']
    LandingHero: typeof import('./components/LandingHero.vue')['default']
    LandingSocial: typeof import('./components/LandingSocial.vue')['default']
    LandingTestimonials: typeof import('./components/LandingTestimonials.vue')['default']
    LandingUsers: typeof import('./components/LandingUsers.vue')['default']
    LogosDiscordIcon: typeof import('~icons/logos/discord-icon')['default']
    LogosTwitter: typeof import('~icons/logos/twitter')['default']
    LucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    LucideCalendar: typeof import('~icons/lucide/calendar')['default']
    LucideMegaphone: typeof import('~icons/lucide/megaphone')['default']
    LucideMoon: typeof import('~icons/lucide/moon')['default']
    LucideSun: typeof import('~icons/lucide/sun')['default']
    MenuCompany: typeof import('./components/MenuCompany.vue')['default']
    MenuMobile: typeof import('./components/MenuMobile.vue')['default']
    MenuPlatform: typeof import('./components/MenuPlatform.vue')['default']
    MenuSolutions: typeof import('./components/MenuSolutions.vue')['default']
    PlatformHero: typeof import('./components/PlatformHero.vue')['default']
    SmartGradient: typeof import('./components/SmartGradient.vue')['default']
    SmartItem: typeof import('./components/SmartItem.vue')['default']
    SmartSpinner: typeof import('./components/SmartSpinner.vue')['default']
  }
}

export { }
